package:
  name: httpie
  version: "0.9.9"

source:
  fn: httpie-0.9.9.tar.gz
  url: https://pypi.python.org/packages/28/93/4ebf2de4bc74bd517a27a600b2b23a5254a20f28e6e36fc876fd98f7a51b/httpie-0.9.9.tar.gz
  md5: 13ed0b79b65e793eb288e563db38b2a2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - httpie = httpie:main
    #
    # Would create an entry point called httpie that calls httpie.main()

    - http = httpie.__main__:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=2.11.0
    - pygments >=2.1.3

  run:
    - python
    - requests >=2.11.0
    - pygments >=2.1.3

test:
  # Python imports
  imports:
    - httpie
    - httpie.output
    - httpie.output.formatters
    - httpie.plugins

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - http --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock
    - pytest
    - pytest-httpbin
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://httpie.org/
  license: BSD License
  summary: 'HTTPie - a CLI, cURL-like tool for humans.'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
