package:
  name: pymorph
  version: 0.96

source:
  fn: pymorph-0.96.tar.gz
  url: https://pypi.python.org/packages/source/p/pymorph/pymorph-0.96.tar.gz
  md5: ed3b9b30b8b0286996e3d26eea8b4bbf

build:
   number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - distribute
    - numpy

test:
  # Python imports
  imports:
    - pymorph

about:
  home: http://luispedro.org/software/pymorph/
  license: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
