package:
  name: aws-ec2-tools
  version: 1.7.1.0

source:
  fn: ec2-api-tools.zip
  url: http://s3.amazonaws.com/ec2-downloads/ec2-api-tools.zip

build: 
  number: 2

  has_prefix_files:
    - bin/ec2-accept-vpc-peering-connection
    - bin/ec2-activate-license
    - bin/ec2-add-group
    - bin/ec2-add-keypair
    - bin/ec2-allocate-address
    - bin/ec2-assign-private-ip-addresses
    - bin/ec2-associate-address
    - bin/ec2-associate-dhcp-options
    - bin/ec2-associate-route-table
    - bin/ec2-attach-internet-gateway
    - bin/ec2-attach-network-interface
    - bin/ec2-attach-volume
    - bin/ec2-attach-vpn-gateway
    - bin/ec2-authorize
    - bin/ec2-bundle-instance
    - bin/ec2-cancel-bundle-task
    - bin/ec2-cancel-conversion-task
    - bin/ec2-cancel-export-task
    - bin/ec2-cancel-reserved-instances-listing
    - bin/ec2-cancel-spot-instance-requests
    - bin/ec2-cmd
    - bin/ec2-confirm-product-instance
    - bin/ec2-copy-image
    - bin/ec2-copy-snapshot
    - bin/ec2-create-customer-gateway
    - bin/ec2-create-dhcp-options
    - bin/ec2-create-group
    - bin/ec2-create-image
    - bin/ec2-create-instance-export-task
    - bin/ec2-create-internet-gateway
    - bin/ec2-create-keypair
    - bin/ec2-create-network-acl
    - bin/ec2-create-network-acl-entry
    - bin/ec2-create-network-interface
    - bin/ec2-create-placement-group
    - bin/ec2-create-reserved-instances-listing
    - bin/ec2-create-route
    - bin/ec2-create-route-table
    - bin/ec2-create-snapshot
    - bin/ec2-create-spot-datafeed-subscription
    - bin/ec2-create-subnet
    - bin/ec2-create-tags
    - bin/ec2-create-volume
    - bin/ec2-create-vpc
    - bin/ec2-create-vpc-peering-connection
    - bin/ec2-create-vpn-connection
    - bin/ec2-create-vpn-connection-route
    - bin/ec2-create-vpn-gateway
    - bin/ec2-deactivate-license
    - bin/ec2-delete-customer-gateway
    - bin/ec2-delete-dhcp-options
    - bin/ec2-delete-disk-image
    - bin/ec2-delete-group
    - bin/ec2-delete-internet-gateway
    - bin/ec2-delete-keypair
    - bin/ec2-delete-network-acl
    - bin/ec2-delete-network-acl-entry
    - bin/ec2-delete-network-interface
    - bin/ec2-delete-placement-group
    - bin/ec2-delete-route
    - bin/ec2-delete-route-table
    - bin/ec2-delete-snapshot
    - bin/ec2-delete-spot-datafeed-subscription
    - bin/ec2-delete-subnet
    - bin/ec2-delete-tags
    - bin/ec2-delete-volume
    - bin/ec2-delete-vpc
    - bin/ec2-delete-vpc-peering-connection
    - bin/ec2-delete-vpn-connection
    - bin/ec2-delete-vpn-connection-route
    - bin/ec2-delete-vpn-gateway
    - bin/ec2-deregister
    - bin/ec2-describe-account-attributes
    - bin/ec2-describe-addresses
    - bin/ec2-describe-availability-zones
    - bin/ec2-describe-bundle-tasks
    - bin/ec2-describe-conversion-tasks
    - bin/ec2-describe-customer-gateways
    - bin/ec2-describe-dhcp-options
    - bin/ec2-describe-export-tasks
    - bin/ec2-describe-group
    - bin/ec2-describe-image-attribute
    - bin/ec2-describe-images
    - bin/ec2-describe-instance-attribute
    - bin/ec2-describe-instance-status
    - bin/ec2-describe-instances
    - bin/ec2-describe-internet-gateways
    - bin/ec2-describe-keypairs
    - bin/ec2-describe-licenses
    - bin/ec2-describe-network-acls
    - bin/ec2-describe-network-interface-attribute
    - bin/ec2-describe-network-interfaces
    - bin/ec2-describe-placement-groups
    - bin/ec2-describe-regions
    - bin/ec2-describe-reserved-instances
    - bin/ec2-describe-reserved-instances-listings
    - bin/ec2-describe-reserved-instances-modifications
    - bin/ec2-describe-reserved-instances-offerings
    - bin/ec2-describe-route-tables
    - bin/ec2-describe-snapshot-attribute
    - bin/ec2-describe-snapshots
    - bin/ec2-describe-spot-datafeed-subscription
    - bin/ec2-describe-spot-instance-requests
    - bin/ec2-describe-spot-price-history
    - bin/ec2-describe-subnets
    - bin/ec2-describe-tags
    - bin/ec2-describe-volume-attribute
    - bin/ec2-describe-volume-status
    - bin/ec2-describe-volumes
    - bin/ec2-describe-vpc-attribute
    - bin/ec2-describe-vpc-peering-connections
    - bin/ec2-describe-vpcs
    - bin/ec2-describe-vpn-connections
    - bin/ec2-describe-vpn-gateways
    - bin/ec2-detach-internet-gateway
    - bin/ec2-detach-network-interface
    - bin/ec2-detach-volume
    - bin/ec2-detach-vpn-gateway
    - bin/ec2-disable-vgw-route-propagation
    - bin/ec2-disassociate-address
    - bin/ec2-disassociate-route-table
    - bin/ec2-enable-vgw-route-propagation
    - bin/ec2-enable-volume-io
    - bin/ec2-fingerprint-key
    - bin/ec2-get-console-output
    - bin/ec2-get-password
    - bin/ec2-import-instance
    - bin/ec2-import-keypair
    - bin/ec2-import-volume
    - bin/ec2-migrate-image
    - bin/ec2-modify-image-attribute
    - bin/ec2-modify-instance-attribute
    - bin/ec2-modify-network-interface-attribute
    - bin/ec2-modify-reserved-instances
    - bin/ec2-modify-snapshot-attribute
    - bin/ec2-modify-subnet-attribute
    - bin/ec2-modify-volume-attribute
    - bin/ec2-modify-vpc-attribute
    - bin/ec2-monitor-instances
    - bin/ec2-purchase-reserved-instances-offering
    - bin/ec2-reboot-instances
    - bin/ec2-register
    - bin/ec2-reject-vpc-peering-connection
    - bin/ec2-release-address
    - bin/ec2-replace-network-acl-association
    - bin/ec2-replace-network-acl-entry
    - bin/ec2-replace-route
    - bin/ec2-replace-route-table-association
    - bin/ec2-report-instance-status
    - bin/ec2-request-spot-instances
    - bin/ec2-reset-image-attribute
    - bin/ec2-reset-instance-attribute
    - bin/ec2-reset-network-interface-attribute
    - bin/ec2-reset-snapshot-attribute
    - bin/ec2-resume-import
    - bin/ec2-revoke
    - bin/ec2-run-instances
    - bin/ec2-start-instances
    - bin/ec2-stop-instances
    - bin/ec2-terminate-instances
    - bin/ec2-unassign-private-ip-addresses
    - bin/ec2-unmonitor-instances
    - bin/ec2-upload-disk-image
    - bin/ec2-version
    - bin/ec2actlic
    - bin/ec2addcgw
    - bin/ec2adddopt
    - bin/ec2addgrp
    - bin/ec2addigw
    - bin/ec2addixt
    - bin/ec2addkey
    - bin/ec2addnacl
    - bin/ec2addnae
    - bin/ec2addnic
    - bin/ec2addpcx
    - bin/ec2addpgrp
    - bin/ec2addrt
    - bin/ec2addrtb
    - bin/ec2addsds
    - bin/ec2addsnap
    - bin/ec2addsubnet
    - bin/ec2addtag
    - bin/ec2addvgw
    - bin/ec2addvol
    - bin/ec2addvpc
    - bin/ec2addvpn
    - bin/ec2allocaddr
    - bin/ec2apcx
    - bin/ec2apip
    - bin/ec2assocaddr
    - bin/ec2assocdopt
    - bin/ec2assocrtb
    - bin/ec2attigw
    - bin/ec2attnic
    - bin/ec2attvgw
    - bin/ec2attvol
    - bin/ec2auth
    - bin/ec2bundle
    - bin/ec2caril
    - bin/ec2cbun
    - bin/ec2cct
    - bin/ec2cim
    - bin/ec2cpi
    - bin/ec2cpimg
    - bin/ec2cpsnap
    - bin/ec2crril
    - bin/ec2csir
    - bin/ec2cvcr
    - bin/ec2cxt
    - bin/ec2daa
    - bin/ec2daddr
    - bin/ec2datt
    - bin/ec2daz
    - bin/ec2dbun
    - bin/ec2dcgw
    - bin/ec2dct
    - bin/ec2ddi
    - bin/ec2ddopt
    - bin/ec2deactlic
    - bin/ec2delcgw
    - bin/ec2deldopt
    - bin/ec2delgrp
    - bin/ec2deligw
    - bin/ec2delkey
    - bin/ec2delnacl
    - bin/ec2delnae
    - bin/ec2delnic
    - bin/ec2delpcx
    - bin/ec2delpgrp
    - bin/ec2delrt
    - bin/ec2delrtb
    - bin/ec2delsds
    - bin/ec2delsnap
    - bin/ec2delsubnet
    - bin/ec2deltag
    - bin/ec2delvgw
    - bin/ec2delvol
    - bin/ec2delvpc
    - bin/ec2delvpn
    - bin/ec2dereg
    - bin/ec2detigw
    - bin/ec2detnic
    - bin/ec2detvgw
    - bin/ec2detvol
    - bin/ec2dgrp
    - bin/ec2diatt
    - bin/ec2digw
    - bin/ec2dim
    - bin/ec2dimatt
    - bin/ec2din
    - bin/ec2dinatt
    - bin/ec2dins
    - bin/ec2disaddr
    - bin/ec2disrtb
    - bin/ec2dkey
    - bin/ec2dlic
    - bin/ec2dnacl
    - bin/ec2dnic
    - bin/ec2dnicatt
    - bin/ec2dpcx
    - bin/ec2dpgrp
    - bin/ec2dre
    - bin/ec2dri
    - bin/ec2dril
    - bin/ec2drim
    - bin/ec2drio
    - bin/ec2drp
    - bin/ec2drtb
    - bin/ec2dsds
    - bin/ec2dsir
    - bin/ec2dsnap
    - bin/ec2dsnapatt
    - bin/ec2dsph
    - bin/ec2dsubnet
    - bin/ec2dtag
    - bin/ec2dva
    - bin/ec2dvcr
    - bin/ec2dvgw
    - bin/ec2dvol
    - bin/ec2dvolatt
    - bin/ec2dvpc
    - bin/ec2dvpn
    - bin/ec2dvs
    - bin/ec2dxt
    - bin/ec2erp
    - bin/ec2evio
    - bin/ec2fp
    - bin/ec2gcons
    - bin/ec2gpass
    - bin/ec2ii
    - bin/ec2iin
    - bin/ec2ikey
    - bin/ec2iv
    - bin/ec2ivol
    - bin/ec2kill
    - bin/ec2matt
    - bin/ec2miatt
    - bin/ec2mim
    - bin/ec2mimatt
    - bin/ec2min
    - bin/ec2minatt
    - bin/ec2mnicatt
    - bin/ec2mri
    - bin/ec2msnapatt
    - bin/ec2msubnetatt
    - bin/ec2mva
    - bin/ec2mvolatt
    - bin/ec2prio
    - bin/ec2ratt
    - bin/ec2reboot
    - bin/ec2reg
    - bin/ec2reladdr
    - bin/ec2rep
    - bin/ec2repnaclassoc
    - bin/ec2repnae
    - bin/ec2reprt
    - bin/ec2reprtbassoc
    - bin/ec2revoke
    - bin/ec2riatt
    - bin/ec2rim
    - bin/ec2rimatt
    - bin/ec2rinatt
    - bin/ec2rnicatt
    - bin/ec2rpcx
    - bin/ec2rsi
    - bin/ec2rsnapatt
    - bin/ec2run
    - bin/ec2start
    - bin/ec2stop
    - bin/ec2tag
    - bin/ec2udi
    - bin/ec2umin
    - bin/ec2upip
    - bin/ec2ver

about:
  home: http://amazonaws.com
  license:  Amazon Software License
