{% set name = "libcprotobuf" %}
{% set version = "3.0.0" %}
{% set version_str = "v3.0.0" %}
{% set sha256 = "f5b3563f118f1d3d6e001705fa7082e8fc3bda50038ac3dff787650795734146" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/google/protobuf/archive/{{ version_str }}/{{ name }}-{{ version_str }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      # Add a patch for non-C++11 support.
      - field_mask_util.cc.patch
      # Adds a patch to get rid of some constants also included in a class.
      - time_util_const_dedup.patch

build:
    number: 0
    # skip the windows python 2.7 and 3.4 build
    # see https://github.com/google/protobuf/issues/1958
    features:
        - vc9                # [win and py27]
        - vc10               # [win and py34]
        - vc14               # [win and py35]

requirements:
    build:
        - git
        - cmake              # [win]
        - autoconf           # [unix]
        - automake           # [unix]
        - libtool            # [unix]
        - pkg-config         # [unix]
        - zlib 1.2.*

    run:
        - zlib 1.2.*

test:
    commands:
        - protoc --help
        - test -f ${PREFIX}/lib/libprotobuf.a                           # [unix]
        - test -f ${PREFIX}/lib/libprotobuf.dylib                       # [osx]
        - test -f ${PREFIX}/lib/libprotobuf.so                          # [linux]
        - if not exist %PREFIX%\\Library\\lib\\libprotobuf.lib exit 1   # [win]

about:
    home: https://developers.google.com/protocol-buffers/
    license: New BSD License
    summary: C library and compiler only - Protocol Buffers - Google's data interchange format

extra:
    # As taken from conda-forge
    recipe-maintainers:
        - dopplershift  # via conda-forge
        - jakirkham     # via conda-forge
        - jjhelmus      # via conda-forge
        - ocefpaf       # via conda-forge
        - bkreider
