package:
  name: perl-app-ssh-cluster
  version: "0.004"

source:
  fn: App-SSH-Cluster-0.004.tar.gz
  url: https://cpan.metacpan.org/authors/id/M/MC/MCMILLHJ/App-SSH-Cluster-0.004.tar.gz
  md5: 926db85b81cd9cebd1487417d42b3b9b
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl
    - perl-extutils-makemaker
    - perl-test-exception
    - perl-list-moreutils
    - perl-moosex-types
    - perl-yaml-tiny
    - perl-moosex-app
    - perl-net-openssh-parallel
    - perl-test-simple

  run:
    - perl
    - perl-moosex-types
    - perl-yaml-tiny
    - perl-moosex-app
    - perl-net-openssh-parallel
    - perl-list-moreutils

test:
  # Perl 'use' tests
  imports:
    - App::SSH::Cluster

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://metacpan.org/release/App-SSH-Cluster
  license: perl_5
  summary: 'CLI to Net::OpenSSH that runs the same command via SSH on many remote servers at the same time'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
