package:
  name: perl-file-slurp-tiny
  version: "0.004"

source:
  fn: File-Slurp-Tiny-0.004.tar.gz
  url: https://cpan.metacpan.org/authors/id/L/LE/LEONT/File-Slurp-Tiny-0.004.tar.gz
  md5: 7575b81543281ea57cdb7e5eb3f73264
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl
    - perl-pathtools
    - perl-extutils-makemaker
    # - perl-carp   # core
    - perl-exporter
    # - perl-file-temp    # core
    - perl-test-simple

  run:
    - perl
    - perl-pathtools
    - perl-exporter
    # - perl-carp   # core

test:
  # Perl 'use' tests
  imports:
    - File::Slurp::Tiny

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://metacpan.org/pod/File-Slurp-Tiny
  license: perl_5
  summary: 'A simple, sane and efficient file slurper [DISCOURAGED]'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
