package:
  name: perl-test-fatal
  version: "0.014"

source:
  fn: Test-Fatal-0.014.tar.gz
  url: https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Test-Fatal-0.014.tar.gz
  md5: 7954f6d2e3607be10c0fbd69063a3d1b
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl
    - perl-pathtools
    - perl-extutils-makemaker
    - perl-exporter
    - perl-test-simple #0.96
    - perl-carp
    - perl-try-tiny
    - perl-test-simple

  run:
    - perl
    - perl-carp
    - perl-try-tiny
    - perl-exporter
    - perl-test-simple

test:
  # Perl 'use' tests
  imports:
    - Test::Fatal

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/rjbs/Test-Fatal
  license: perl_5
  summary: 'incredibly simple helpers for testing code with exceptions'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
