package:
  name: perl-test-exception
  version: "0.43"

source:
  fn: Test-Exception-0.43.tar.gz
  url: https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Test-Exception-0.43.tar.gz
  md5: 572d355026fb0b87fc2b8c64b83cada0
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl
    - perl-extutils-makemaker
    - perl-exporter
    # - perl-test-harness   # core
    # - perl-base      # core?  maybe?
    # - perl-carp      # core
    - perl-sub-uplevel
    - perl-test-simple

  run:
    - perl
    - perl-test-harness
    - perl-exporter
    - perl-base
    # - perl-carp       # core
    - perl-sub-uplevel
    - perl-test-simple

test:
  # Perl 'use' tests
  imports:
    - Test::Exception

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/Test-More/test-exception
  license: perl_5
  summary: 'Test exception-based code'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
