{% set version = '1.21' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-desolve
  version: {{ version|replace("-", "_") }}

source:
  fn: deSolve_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/deSolve_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/deSolve/deSolve_{{ version }}.tar.gz


  sha256: 45c372d458fe4c7c11943d4c409517849b1be6782dc05bd9a74b066e67250c63
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: scatterplot3d
requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('deSolve')"  # [not win]
    - "\"%R%\" -e \"library('deSolve')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://desolve.r-forge.r-project.org/
  license: GPL (>= 2)
  summary: Functions that solve initial value problems of a system of first-order ordinary differential
    equations ('ODE'), of partial differential equations ('PDE'), of differential algebraic
    equations ('DAE'), and of delay differential equations.  The functions provide an
    interface to the FORTRAN functions 'lsoda', 'lsodar', 'lsode', 'lsodes' of the 'ODEPACK'
    collection, to the FORTRAN functions 'dvode', 'zvode' and 'daspk' and a C-implementation
    of solvers of the 'Runge-Kutta' family with fixed or variable time steps.  The package
    contains routines designed for solving 'ODEs' resulting from 1-D, 2-D and 3-D partial
    differential equations ('PDE') that have been converted to 'ODEs' by numerical differencing.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: deSolve
# Version: 1.21
# Title: Solvers for Initial Value Problems of Differential Equations ('ODE', 'DAE', 'DDE')
# Authors@R: c(person("Karline","Soetaert", role = c("aut"),  email = "karline.soetaert@nioz.nl"), person("Thomas","Petzoldt", role = c("aut", "cre"), email = "thomas.petzoldt@tu-dresden.de"), person("R. Woodrow","Setzer", role = c("aut"), email = "setzer.woodrow@epa.gov"), person("odepack authors", role = "cph"))
# Author: Karline Soetaert [aut], Thomas Petzoldt [aut, cre], R. Woodrow Setzer [aut], odepack authors [cph]
# Maintainer: Thomas Petzoldt <thomas.petzoldt@tu-dresden.de>
# Depends: R (>= 2.15.0)
# Imports: methods, graphics, grDevices, stats
# Suggests: scatterplot3d
# Description: Functions that solve initial value problems of a system of first-order ordinary differential equations ('ODE'), of partial differential equations ('PDE'), of differential algebraic equations ('DAE'), and of delay differential equations.  The functions provide an interface to the FORTRAN functions 'lsoda', 'lsodar', 'lsode', 'lsodes' of the 'ODEPACK' collection, to the FORTRAN functions 'dvode', 'zvode' and 'daspk' and a C-implementation of solvers of the 'Runge-Kutta' family with fixed or variable time steps.  The package contains routines designed for solving 'ODEs' resulting from 1-D, 2-D and 3-D partial differential equations ('PDE') that have been converted to 'ODEs' by numerical differencing.
# License: GPL (>= 2)
# URL: http://desolve.r-forge.r-project.org/
# LazyData: yes
# NeedsCompilation: yes
# Packaged: 2018-05-08 19:29:44 UTC; user
# Repository: CRAN
# Date/Publication: 2018-05-09 09:38:07 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
