package:
  name: perl-moosex-app
  version: "1.33"

source:
  fn: MooseX-App-1.33.tar.gz
  url: https://cpan.metacpan.org/authors/id/M/MA/MAROS/MooseX-App-1.33.tar.gz
  md5: f52717ab0bc69c57c3d0d60deb5203df
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl
    - perl-module-pluggable
    - perl-extutils-makemaker
    - perl-path-class
    - perl-config-any
    - perl-test-most
    - perl-moosex-types-path-class
    - perl-moose
    - perl-test-nowarnings
    - perl-pod-elemental
    - perl-namespace-autoclean
    - perl-scalar-list-utils

  run:
    - perl
    - perl-module-pluggable
    - perl-path-class
    - perl-config-any
    - perl-namespace-autoclean
    - perl-moosex-types-path-class
    - perl-moose
    - perl-pod-elemental
    - perl-scalar-list-utils

test:
  # Perl 'use' tests
  imports:
    - MooseX::App
    - MooseX::App::Command
    - MooseX::App::Exporter
    - MooseX::App::Message::Block
    - MooseX::App::Message::BlockColor
    - MooseX::App::Message::Envelope
    - MooseX::App::Meta::Role::Attribute::Option
    - MooseX::App::Meta::Role::Class::Base
    - MooseX::App::Meta::Role::Class::Command
    - MooseX::App::Meta::Role::Class::Documentation
    - MooseX::App::Meta::Role::Class::Simple
    - MooseX::App::Null
    - MooseX::App::ParsedArgv
    - MooseX::App::ParsedArgv::Element
    - MooseX::App::Plugin::BashCompletion
    - MooseX::App::Plugin::BashCompletion::Command
    - MooseX::App::Plugin::BashCompletion::Meta::Class
    - MooseX::App::Plugin::Color
    - MooseX::App::Plugin::Color::Meta::Class
    - MooseX::App::Plugin::Config
    - MooseX::App::Plugin::Config::Meta::Class
    - MooseX::App::Plugin::ConfigHome
    - MooseX::App::Plugin::ConfigHome::Meta::Class
    - MooseX::App::Plugin::Depends
    - MooseX::App::Plugin::Depends::Meta::Attribute
    - MooseX::App::Plugin::Depends::Meta::Class
    - MooseX::App::Plugin::Env
    - MooseX::App::Plugin::Fuzzy
    - MooseX::App::Plugin::Man
    - MooseX::App::Plugin::Man::Command
    - MooseX::App::Plugin::Man::Meta::Class
    - MooseX::App::Plugin::MutexGroup
    - MooseX::App::Plugin::MutexGroup::Meta::Attribute
    - MooseX::App::Plugin::MutexGroup::Meta::Class
    - MooseX::App::Plugin::Term
    - MooseX::App::Plugin::Term::Meta::Attribute
    - MooseX::App::Plugin::Term::Meta::Class
    - MooseX::App::Plugin::Typo
    - MooseX::App::Plugin::Typo::Meta::Class
    - MooseX::App::Plugin::Version
    - MooseX::App::Plugin::Version::Command
    - MooseX::App::Plugin::Version::Meta::Class
    - MooseX::App::Role
    - MooseX::App::Role::Base
    - MooseX::App::Role::Common
    - MooseX::App::Simple
    - MooseX::App::Utils

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://metacpan.org/pod/MooseX-App
  license: perl_5
  summary: 'Write user-friendly command line apps with even less suffering'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
