package:
  name: perl-list-moreutils
  version: "0.413"

source:
  fn: List-MoreUtils-0.413.tar.gz
  url: https://cpan.metacpan.org/authors/id/R/RE/REHSACK/List-MoreUtils-0.413.tar.gz
  md5: bc577c86455e2d1397187bce286a53b9
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl
    - perl-pathtools
    - perl-base
    - perl-extutils-makemaker
    - perl-carp
    - perl-file-path    # core
    - perl-exporter-tiny
    - perl-xsloader
    - perl-test-simple #0.96
    - perl-ipc-cmd

  run:
    - perl
    - perl-exporter-tiny
    - perl-xsloader

test:
  # Perl 'use' tests
  imports:
    - List::MoreUtils
    - List::MoreUtils::PP
    - List::MoreUtils::XS

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://metacpan.org/release/List-MoreUtils
  license: perl_5
  summary: 'Provide the stuff missing in List::Util'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
