package:
  name: prompt_toolkit
  version: "1.0.14"

source:
  fn: prompt_toolkit-1.0.14.tar.gz
  url: https://pypi.python.org/packages/55/56/8c39509b614bda53e638b7500f12577d663ac1b868aef53426fc6a26c3f5/prompt_toolkit-1.0.14.tar.gz
  md5: f24061ae133ed32c6b764e92bd48c496
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - prompt_toolkit = prompt_toolkit:main
    #
    # Would create an entry point called prompt_toolkit that calls prompt_toolkit.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six >=1.9.0
    - wcwidth

  run:
    - python
    - six >=1.9.0
    - wcwidth

test:
  # Python imports
  imports:
    - prompt_toolkit
    - prompt_toolkit.clipboard
    - prompt_toolkit.contrib
    - prompt_toolkit.contrib.completers
    - prompt_toolkit.contrib.regular_languages
    - prompt_toolkit.contrib.telnet
    - prompt_toolkit.contrib.validators
    - prompt_toolkit.eventloop
    - prompt_toolkit.filters
    - prompt_toolkit.key_binding
    - prompt_toolkit.key_binding.bindings
    - prompt_toolkit.layout
    - prompt_toolkit.styles
    - prompt_toolkit.terminal

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jonathanslenders/python-prompt-toolkit
  license: BSD License
  summary: 'Library for building powerful interactive command lines in Python'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
