package:
  name: perl-class-method-modifiers
  version: "2.11"

source:
  fn: Class-Method-Modifiers-2.11.tar.gz
  url: http://cpan.metacpan.org/authors/id/E/ET/ETHER/Class-Method-Modifiers-2.11.tar.gz
  md5: c6982e9e89325713d5afaff82cfe1744
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl
    - perl-pathtools
    - perl-extutils-makemaker
    - perl-test-requires
    - perl-carp
    - perl-test-fatal
    - perl-if
    - perl-exporter
    - perl-base
    - perl-test-simple

  run:
    - perl
    - perl-base
    - perl-carp
    - perl-exporter

test:
  # Perl 'use' tests
  imports:
    - Class::Method::Modifiers

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/moose/Class-Method-Modifiers
  license: perl_5
  summary: 'Provides Moose-like method modifiers'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
