{% set name = "magic-wormhole" %}
{% set version = "0.10.5" %}
{% set hash_type = "sha256" %}
{% set hash_value = "9558ea1f3551e535deec3462cd5c8391cb32ebb12ecd8b40b36861dbee4917ee" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - wormhole = wormhole.cli.cli:wormhole
    - wormhole-server = wormhole.server.cli:server
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - spake2 ==0.8
    - pynacl
    - six
    - attrs >=16.3.0
    - twisted[tls] >=17.5.0
    - autobahn[twisted] >=0.14.1
    - automat
    - hkdf
    - tqdm >=4.13.0
    - click
    - humanize
    - ipaddress
    - txtorcon >=0.19.3
  run:
    - python
    - spake2 ==0.8
    - pynacl
    - six
    - attrs >=16.3.0
    - twisted[tls] >=17.5.0
    - autobahn[twisted] >=0.14.1
    - automat
    - hkdf
    - tqdm >=4.13.0
    - click
    - humanize
    - ipaddress
    - txtorcon >=0.19.3

test:
  imports:
    - wormhole
    - wormhole.cli
    - wormhole.server
    - wormhole.test
  commands:
    - wormhole --help
    - wormhole-server --help

about:
  home: https://github.com/warner/magic-wormhole
  license: MIT
  license_family: MIT
  license_file: ''
  summary: Securely transfer data between computers
  description: 'UNKNOWN



    '
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
