package:
  name: m2crypto
  version: !!str 0.22.3

source:
  fn: M2Crypto-0.22.3.tar.gz
  url: https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.22.3.tar.gz
  md5: 573f21aaac7d5c9549798e72ffcefedd

  patches:
    - setup.patch


build:
  preserve_egg_dir: yes
  number:  {{environ.get('BINSTAR_BUILD', 1)}}

requirements:
  build:
    - python
    - setuptools
    - swig
    - openssl

  run:
    - python
    - distribute
    - openssl

test:
  imports:
    - M2Crypto
    - M2Crypto.SSL

about:
  home: https://github.com/martinpaljak/M2Crypto
  license: MIT License
  summary: 'M2Crypto: A Python crypto and SSL toolkit'

