package:
  name: argh
  version: !!str 0.24.1

source:
  fn: argh-0.24.1.tar.gz
  url: https://pypi.python.org/packages/source/a/argh/argh-0.24.1.tar.gz
  md5: 67ef29c2a32b206228933d94cdfeda96

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - argh

about:
  home: http://github.com/neithere/argh/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'An unobtrusive argparse wrapper with natural syntax'
