package:
  name: parsimonious
  version: "0.7.0"

source:
  fn: parsimonious-0.7.0.tar.gz
  url: https://pypi.python.org/packages/11/db/06a1d0a41b4d236cd84fb27fced4479645b1fb6100501e03accde2804e51/parsimonious-0.7.0.tar.gz
  md5: 7fce85c276a07066337990c344b3ba85
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - parsimonious = parsimonious:main
    #
    # Would create an entry point called parsimonious that calls parsimonious.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  # Python imports
  imports:
    - parsimonious
    - parsimonious.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/erikrose/parsimonious
  license: MIT License
  summary: '(Soon to be) the fastest pure-Python PEG parser I could muster'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
