package:
  name: perl-exporter
  version: "5.68"

source:
  #fn: Exporter-5.68.tar.gz
  #url: http://cpan.metacpan.org/authors/id/T/TO/TODDR/Exporter-5.68.tar.gz
  #md5: None
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - Exporter
    - Exporter::Heavy

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://metacpan.org/pod/Exporter
  license: perl_5
  summary: 'Implements default import method for modules'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
