{% set name = "watchman" %}
{% set version = "4.9.0" %}

# 
#  This only works on OSX at the moment
# 

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: v4.9.0
  git_url: https://github.com/facebook/watchman.git
  patches:
    - patch1.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - automake
    - libtool
    - pkg-config
  host:
    - openssl

about:
    home: git clone https://github.com/facebook/watchman.git

extra:
    recipe-maintainers:
      - bkreider

