{% set name = "step" %}
{% set version = "0.13.3" %}

# 
#  This only works on OSX at the moment
# 

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: v0.13.3
  git_url: https://github.com/smallstep/cli.git

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - clangxx_osx-64
    - make

test:
    commands:
        - test -x $PREFIX/bin/step

about:
    home: https://github.com/smallstep/cli/
    license: Apache 2.0
    summary: |
      zero trust swiss army knife for automated certificate management.
      
    description: | 
        step is a zero trust swiss army knife that integrates with step-ca for
        automated certificate management. It's an easy-to-use and hard-to-misuse
        utility for building, operating, and automating systems that use zero
        trust technologies like authenticated encryption (X.509, TLS), single
        sign-on (OAuth OIDC, SAML), multi-factor authentication (OATH OTP,
        FIDO U2F), encryption mechanisms (JSON Web Encryption, NaCl), and
        verifiable claims (JWT, SAML assertions).

    dev_url: https://github.com/smallstep/cli/
    doc_url: https://smallstep.com/docs/getting-started/

extra:
    recipe-maintainers:
      - bkreider

