package:
  name: perl-test-requires
  version: "0.10"

source:
  fn: Test-Requires-0.10.tar.gz
  url: https://cpan.metacpan.org/authors/id/T/TO/TOKUHIROM/Test-Requires-0.10.tar.gz
  md5: 0d5da779609d0c8fa6f796b45ff8c6f3
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl
    - perl-extutils-makemaker
    - perl-test-simple #0.47
    - perl-test-simple

  run:
    - perl
    - perl-test-simple #0.47

test:
  # Perl 'use' tests
  imports:
    - Test::Requires

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/tokuhirom/Test-Requires
  license: perl_5
  summary: 'Checks to see if the module can be loaded'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
