source:
  fn: openssl-1.0.1h.tar.gz
  url: http://www.openssl.org/source/openssl-1.0.1h.tar.gz
  md5: 8d6d684a9430d5cc98a62a5d8fbda8cf

about:
  home: http://www.openssl.org/
  license: Apache-style (http://www.openssl.org/source/license.html)
