package:
  name: perl-yaml-tiny
  version: "1.69"

source:
  fn: YAML-Tiny-1.69.tar.gz
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/YAML-Tiny-1.69.tar.gz
  md5: 7deacd0ee428038407ccc5cd0b50f66f
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl
    - perl-pathtools
    - perl-extutils-makemaker
    - perl-test-simple #0.88
    - perl-exporter
    - perl-getopt-long
    - perl-io
    - perl-base
    - perl-carp
    - perl-file-temp #0.19
    - perl-lib
    - perl-json-pp
    - perl-scalar-list-utils

  run:
    - perl
    - perl-exporter
    - perl-carp
    - perl-scalar-list-utils

test:
  # Perl 'use' tests
  imports:
    - YAML::Tiny

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/Perl-Toolchain-Gang/YAML-Tiny
  license: perl_5
  summary: 'Read/Write YAML files with as little code as possible'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
