package:
  name: udunits
  version: 2.1.24

source:
  fn: udunits-2.1.24.tar.gz
  url: ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.1.24.tar.gz

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  license: Custom - Attribution and patent protection
