package:
  name: perl-tk
  version: "804.033"

source:
  fn: Tk-804.033.tar.gz
  url: https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Tk-804.033.tar.gz
  md5: 4c6d281ca9c6c2349e5cf84394e638fa
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl
    - perl-encode
    - perl-extutils-makemaker
    # - perl-test-simple  # core lib

  run:
    - perl
    - perl-encode
    # - perl-test-simple # core lib

test:
  # Perl 'use' tests
  
  # Versions are completely broken for Tk
  # perl Tk tracks the tk major version, hence the 80y.xxx
  #    but each submodule only has a y.xx version number.  The version numbers will never match
  
  imports:
    - Tk
    #- Tk::Adjuster
    #- Tk::Adjuster::Item
    #- Tk::After
    #- Tk::Animation
    #- Tk::Balloon
    #- Tk::Bitmap
    #- Tk::BrowseEntry
    #- Tk::Button
    #- Tk::Canvas
    #- Tk::Checkbutton
    #- Tk::Clipboard
    #- Tk::CmdLine
    #- Tk::ColorDialog
    #- Tk::ColorEditor
    #- Tk::ColorSelect
    #- Tk::Compound
    #- Tk::Configure
    #- Tk::Derived
    #- Tk::Dialog
    #- Tk::DialogBox
    #- Tk::DirTree
    #- Tk::DirTreeDialog
    #- Tk::Dirlist
    #- Tk::DragDrop
    #- Tk::DragDrop::Common
    #- Tk::DragDrop::Local
    #- Tk::DragDrop::Rect
    #- Tk::DragDrop::SunConst
    #- Tk::DragDrop::SunDrop
    #- Tk::DragDrop::SunSite
    #- Tk::DragDrop::Win32Drop
    #- Tk::DragDrop::Win32Site
    #- Tk::DragDrop::XDNDDrop
    #- Tk::DragDrop::XDNDSite
    #- Tk::DropSite
    #- Tk::DummyEncode
    #- Tk::DummyEncode::X11ControlChars
    #- Tk::DummyEncode::iso8859_1
    #- Tk::English
    #- Tk::Entry
    #- Tk::ErrorDialog
    #- Tk::Event
    #- Tk::Event::IO
    #- Tk::FBox
    #- Tk::FileSelect
    #- Tk::FloatEntry
    #- Tk::Font
    #- Tk::Frame
    #- Tk::HList
    #- Tk::IO
    #- Tk::IconList
    #- Tk::Image
    #- Tk::InputO
    #- Tk::ItemStyle
    #- Tk::JPEG
    #- Tk::LabEntry
    #- Tk::LabFrame
    ##- Tk::LabRadiobutton
    #- Tk::Label
    ##- Tk::LabeledEntryLabeledRadiobutton
    #- Tk::Labelframe
    #- Tk::Listbox
    #- Tk::MMtry
    #- Tk::MMutil
    #- Tk::MainWindow
    #- Tk::MakeDepend
    #- Tk::Menu
    ##- Tk::Menu::Button
    ##- Tk::Menu::Cascade
    ##- Tk::Menu::Checkbutton
    ##- Tk::Menu::Item
    ##- Tk::Menu::Radiobutton
    ##- Tk::Menu::Separator
    #- Tk::Menubar
    #- Tk::Menubutton
    #- Tk::Message
    #- Tk::MsgBox
    #- Tk::Mwm
    #- Tk::NBFrame
    #- Tk::NoteBook
    #- Tk::Optionmenu
    #- Tk::PNG
    #- Tk::Pane
    #- Tk::Panedwindow
    #- Tk::Photo
    #- Tk::Pixmap
    #- Tk::Pretty
    #- Tk::ProgressBar
    #- Tk::ROText
    #- Tk::Radiobutton
    #- Tk::Region
    #- Tk::Reindex
    #- Tk::ReindexedROText
    #- Tk::ReindexedText
    #- Tk::Scale
    #- Tk::Scrollbar
    #- Tk::Spinbox
    #- Tk::Stats
    #- Tk::Submethods
    #- Tk::TList
    #- Tk::Table
    #- Tk::Text
    #- Tk::Text::Tag
    #- Tk::TextEdit
    #- Tk::TextList
    #- Tk::TextUndo
    #- Tk::Tiler
    #- Tk::TixGrid
    #- Tk::Toplevel
    #- Tk::Trace
    #- Tk::Tree
    #- Tk::Widget
    #- Tk::WinPhoto
    #- Tk::Wm
    #- Tk::X
    #- Tk::X11Font
    #- Tk::Xlib
    #- Tk::Xrm
    #- Tk::install
    #- Tk::widgets

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://metacpan.org/pod/Tk
  license: unrestricted
  summary: 'Tk - a Graphical User Interface Toolkit'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
