package:
  name: http-prompt
  version: "0.9.3"

source:
  fn: http-prompt-0.9.3.tar.gz
  url: https://pypi.python.org/packages/12/fa/9b10a4260779633d0342aab059a7681e26ba91810d0134e8667b3c7e8b1e/http-prompt-0.9.3.tar.gz
  md5: 015859dd11dcc1363d5d8c29920014d5
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - http-prompt = http-prompt:main
    #
    # Would create an entry point called http-prompt that calls http-prompt.main()

    - http-prompt=http_prompt.cli:cli

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - click >=5.0
    - httpie >=0.9.2
    - parsimonious >=0.6.2
    - prompt_toolkit >=0.60
    - pygments >=2.1.0
    - six >=1.10.0

  run:
    - python
    - setuptools
    - click >=5.0
    - httpie >=0.9.2
    - parsimonious >=0.6.2
    - prompt_toolkit >=0.60
    - pygments >=2.1.0
    - six >=1.10.0

test:
  # Python imports
  imports:
    - http_prompt
    - http_prompt.context

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - http-prompt --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/eliangcs/http-prompt
  license: MIT License
  summary: 'An interactive HTTP command-line client'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
