package:
  name: perl-constant
  version: "1.27"

source:
  #fn: 
  #url: 
  #md5: 
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - constant

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://metacpan.org/module/constant
  license: perl_5
  summary: 'Perl pragma to declare constants'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
