{% set version = '0.7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gsubfn
  version: {{ version|replace("-", "_") }}

source:
  fn: gsubfn_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/gsubfn_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/gsubfn/gsubfn_{{ version }}.tar.gz


  sha256: 89351df9e65722d2862f26a0a3985666de3c86e8400808ced8a6eb6e165a4602
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: boot, chron, grid, lattice, quantreg, svUnit, tcltk, zoo
requirements:
  build:
    - r-base
    - r-proto

  run:
    - r-base
    - r-proto

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('gsubfn')"  # [not win]
    - "\"%R%\" -e \"library('gsubfn')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ggrothendieck/gsubfn
  license: GPL (>= 2)
  summary: The gsubfn function is like gsub but can take a replacement  function or certain other
    objects instead of the replacement string. Matches and back references are input
    to the replacement function and  replaced by the function output.   gsubfn can be
    used to split strings  based on content rather than delimiters and for quasi-perl-style
    string  interpolation. The package also has facilities for translating formulas  to
    functions and allowing such formulas in function calls instead of  functions.  This
    can be used with R functions such as apply, sapply, lapply, optim, integrate, xyplot,
    Filter and any other function that  expects another function as an input argument
    or functions like cat or sql calls that may involve strings where substitution is
    desirable. There is also a facility for returning multiple objects from functions
    and a version of transform that allows the RHS to refer to LHS used in the same
    transform.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: gsubfn
# Version: 0.7
# Date: 2018-03-15
# Title: Utilities for Strings and Function Arguments
# Author: G. Grothendieck
# Maintainer: G. Grothendieck <ggrothendieck@gmail.com>
# Description: The gsubfn function is like gsub but can take a replacement  function or certain other objects instead of the replacement string. Matches and back references are input to the replacement function and  replaced by the function output.   gsubfn can be used to split strings  based on content rather than delimiters and for quasi-perl-style string  interpolation. The package also has facilities for translating formulas  to functions and allowing such formulas in function calls instead of  functions.  This can be used with R functions such as apply, sapply, lapply, optim, integrate, xyplot, Filter and any other function that  expects another function as an input argument or functions like cat or sql calls that may involve strings where substitution is desirable. There is also a facility for returning multiple objects from functions and a version of transform that allows the RHS to refer to LHS used in the same transform.
# BugReports: https://github.com/ggrothendieck/gsubfn/issues
# Depends: proto
# Suggests: boot, chron, grid, lattice, quantreg, svUnit, tcltk, zoo
# License: GPL (>= 2)
# URL: https://github.com/ggrothendieck/gsubfn
# NeedsCompilation: no
# Packaged: 2018-03-15 23:17:54 UTC; Louis
# Repository: CRAN
# Date/Publication: 2018-03-16 08:58:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
