package:
  name: watchdog
  version: !!str 0.8.0

source:
  fn: watchdog-0.8.0.tar.gz
  url: https://pypi.python.org/packages/source/w/watchdog/watchdog-0.8.0.tar.gz
  md5: 8d3b7acc8a6988f70598002deb49ebf4

  # Remove requirements from setuptools
  patches:
    - setup.patch

build:
  #preserve_egg_dir: True
  entry_points:
    - watchmedo = watchdog.watchmedo:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyyaml
    - argh
    - pathtools
    # argparse is merged into Python 2.7 in the Python 2x series
    - argparse        # [py26]

    # Python 2.6 and below have the broken/non-existent kqueue implementations
    - select_backport # [py26 and osx]  

test:
  imports:
    - watchdog
    - watchdog.observers
    - watchdog.tricks
    - watchdog.utils

  commands:
    - watchmedo --help

about:
  home: http://github.com/gorakhargosh/watchdog
  license: ache Software License
  summary: 'Filesystem events monitoring'
