package:
  name: perl-net-openssh-parallel
  version: "0.14"

source:
  fn: Net-OpenSSH-Parallel-0.14.tar.gz
  url: https://cpan.metacpan.org/authors/id/S/SA/SALVA/Net-OpenSSH-Parallel-0.14.tar.gz
  md5: 71c1eb22b61d32ef12dfa5e6bcd53235
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl
    - perl-extutils-makemaker
    - perl-net-openssh

  run:
    - perl
    - perl-net-openssh

test:
  # Perl 'use' tests
  imports:
    - Net::OpenSSH::Parallel
    - Net::OpenSSH::Parallel::Constants

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://metacpan.org/pod/Net-OpenSSH-Parallel
  license: unknown
  summary: 'Run SSH jobs in parallel'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
