package:
  name: perl-sub-uplevel
  version: "0.25"

source:
  fn: Sub-Uplevel-0.25.tar.gz
  url: https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Sub-Uplevel-0.25.tar.gz
  md5: 5d0752dbfa94d0c91b25a264f47f5675
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl
    - perl-pathtools
    - perl-extutils-makemaker
    # - perl-carp     # core
    - perl-exporter
    # - perl-constant      # core
    - perl-test-simple

  run:
    - perl
    # - perl-carp   # core
    - perl-constant

test:
  # Perl 'use' tests
  imports:
    - Sub::Uplevel

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/dagolden/Sub-Uplevel
  license: perl_5
  summary: 'apparently run a function in a higher stack frame'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
