package:
  name: logstash
  version: 1.3.3

source:
  fn: logstash-1.3.3-flatjar.jar
  url: https://download.elasticsearch.org/logstash/logstash/logstash-1.3.3-flatjar.jar

build:
   number: 1

about:
  home: https://github.com/elasticsearch/logstash
  license: Apache 2
