{% set version = '1.3-9' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-elliptic
  version: {{ version|replace("-", "_") }}

source:
  fn: elliptic_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/elliptic_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/elliptic/elliptic_{{ version }}.tar.gz


  sha256: 81db271d891afbe13b4cc44a67573ddfef6df9ce7c10f87895fdd074219d813f
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: emulator, calibrator
requirements:
  build:
    - r-base
    - r-mass

  run:
    - r-base
    - r-mass

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('elliptic')"  # [not win]
    - "\"%R%\" -e \"library('elliptic')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/RobinHankin/elliptic.git
  license: GPL-2
  summary: A suite of elliptic and related functions including Weierstrass and Jacobi forms.  Also
    includes various tools for manipulating and visualizing complex functions.
  license_family: GPL2

# The original CRAN metadata for this package was:

# Package: elliptic
# Version: 1.3-9
# Date: 2018-08-03
# Title: Weierstrass and Jacobi Elliptic Functions
# Author: Robin K. S. Hankin
# Depends: R (>= 2.5.0)
# Imports: MASS
# Suggests: emulator, calibrator
# SystemRequirements: pari/gp
# Description:  A suite of elliptic and related functions including Weierstrass and Jacobi forms.  Also includes various tools for manipulating and visualizing complex functions.
# Maintainer: Robin K. S. Hankin <hankin.robin@gmail.com>
# License: GPL-2
# URL: https://github.com/RobinHankin/elliptic.git
# BugReports: https://github.com/RobinHankin/elliptic/issues
# NeedsCompilation: no
# Packaged: 2018-08-03 07:23:33 UTC; rhankin
# Repository: CRAN
# Date/Publication: 2018-08-03 10:10:12 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
