package:
  name: salt
  version: 2014.1.13

source:
  git_tag: v2014.1.13
  git_url: https://github.com/saltstack/salt.git

build:
    number:  {{environ.get('BINSTAR_BUILD', 1)}}

requirements:
  build:
    - python

  run:
    - python
    - jinja2
    - msgpack-python
    - pycrypto
    - pyyaml
    - pyzmq >=2.2.0 
    - markupsafe
    - apache-libcloud 0.14*
    - requests
    - python-apt # [linux]

test:
    commands:
        - salt --version


about:
  home: http://saltstack.com
