package:
  name: autopkg-jessepeterson-recipes
  version: 0.5.1

source:
  git_url: https://github.com/autopkg/jessepeterson-recipes.git

build:
  number: {{ environ.get('BINSTAR_BUILD', 1) }}

  # Make copies of config files, so they are safe to edit
  no_link:  Library/*

about:
  home: https://github.com/autopkg/jessepeterson-recipes.git
  license: Apache 2.0
