package:
  name: selenium
  version: "3.4.2"

source:
  fn: selenium-3.4.2.tar.gz
  url: https://pypi.python.org/packages/47/63/611503113c00cb3ba0ab310567b4f7d7c2a3178e7ebc07f66ae4b997d56a/selenium-3.4.2.tar.gz
  md5: 5b30ae75463e0e951c39ebcb2ebbd573
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - selenium = selenium:main
    #
    # Would create an entry point called selenium that calls selenium.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver
    - selenium.webdriver.android
    - selenium.webdriver.chrome
    - selenium.webdriver.common
    - selenium.webdriver.common.html5
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.ie
    - selenium.webdriver.opera
    - selenium.webdriver.phantomjs
    - selenium.webdriver.remote
    - selenium.webdriver.support

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/SeleniumHQ/selenium/
  license: Apache Software License
  summary: 'Python bindings for Selenium'
  license_family: APACHE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
