{% set version = '2.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-btyd
  version: {{ version|replace("-", "_") }}

source:
  fn: BTYD_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/BTYD_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/BTYD/BTYD_{{ version }}.tar.gz


  sha256: 870450d167782f463c0da2ba7b9c2e4f8baa6b76b91fe208e3f5b4ac9f665f8f
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr
requirements:
  build:
    - r-base
    - r-matrix
    - r-hypergeo

  run:
    - r-base
    - r-matrix
    - r-hypergeo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('BTYD')"  # [not win]
    - "\"%R%\" -e \"library('BTYD')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: wcai.wharton.upenn.edu
  license: GPL-3
  summary: This package contains functions for data preparation, parameter estimation, scoring,
    and plotting for the BG/BB, BG/NBD and Pareto/NBD models.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: BTYD
# Type: Package
# Title: Implementing Buy 'Til You Die Models
# Version: 2.4
# Date: 2014-11-06
# Authors@R: c(person("Lukasz", "Dziurzynski", role="aut"), person("Edward", "Wadsworth", role="aut"), person("Peter", "Fader", role="ctb"), person("Elea", "McDonnell Feit", role="ctb"), person("Daniel", "McCarthy", role=c("aut","cre","ctb"),  email="danielmc@wharton.upenn.edu"), person("Bruce", "Hardie", role="ctb"), person("Arun", "Gopalakrishnan", role="ctb"), person("Eric", "Schwartz", role="ctb"), person("Yao", "Zhang", role="ctb"))
# Maintainer: Daniel McCarthy <danielmc@wharton.upenn.edu>
# URL: wcai.wharton.upenn.edu
# Description: This package contains functions for data preparation, parameter estimation, scoring, and plotting for the BG/BB, BG/NBD and Pareto/NBD models.
# License: GPL-3
# Collate: 'bgbb.R' 'bgnbd.R' 'pnbd.R' 'dc.R' 'spend.R'
# Depends: hypergeo
# Imports: Matrix
# Suggests: knitr
# VignetteBuilder: knitr
# Packaged: 2014-11-07 03:11:39 UTC; danielmc
# Author: Lukasz Dziurzynski [aut], Edward Wadsworth [aut], Peter Fader [ctb], Elea McDonnell Feit [ctb], Daniel McCarthy [aut, cre, ctb], Bruce Hardie [ctb], Arun Gopalakrishnan [ctb], Eric Schwartz [ctb], Yao Zhang [ctb]
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-11-07 09:59:40

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
